<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{%block title%} 追剧神器 {%endblock%}</title>

<link href="/public/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/public/css/datepicker3.css" rel="stylesheet"/>
<link href="/public/css/bootstrap-table.css" rel="stylesheet"/>
<link href="/public/css/styles.css" rel="stylesheet"/>

<script src="/public/js/jquery-1.11.1.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>
<script src="/public/js/bootstrap-datepicker.js"></script>
<script src="/public/js/bootstrap-table.js"></script>
<script src="/public/js/chart.min.js"></script>
<script src="/public/js/easypiechart.js"></script>
<script src="/public/js/easypiechart-data.js"></script>
<script src="/public/js/base64.js"></script>

<!--[if lt IE 9]>
<script src="/public/js/html5shiv.min.js"></script>
<script src="/public/js/respond.min.js"></script>
<![endif]-->

</head>

<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-39257204-1', 'auto');
    ga('send', 'pageview');

</script>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Lumino</span>Admin</a>
                <ul class="user-menu">
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> User <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
                            <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div><!-- /.container-fluid -->
    </nav>

    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li role="presentation" class="divider"></li>
            <li class="active"><a href="#"><span class="glyphicon glyphicon-dashboard"></span> SERIAL </a></li>
            <li role="presentation" class="divider"></li>
        </ul>
        <div class="attribution"><a target="_blank" href="http://www.miibeian.gov.cn/">京ICP备11040178号</a></div>
    </div><!--/.sidebar-->

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			

    {%block main%}
    {%endblock%}

    </div><!--/.main-->


    <script>
        !function ($) {
            $(document).on("click","ul.nav li.parent > a > span.icon", function(){		  
                $(this).find('em:first').toggleClass("glyphicon-minus");	  
            }); 
            $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
        }(window.jQuery);

        $(window).on('resize', function () {
            if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
        })
        $(window).on('resize', function () {
            if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
        })
    </script>	
</body>

</html>
