<div class="row">
    <ol class="breadcrumb">
        <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">EPISODE</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">EPISODE</h1>
    </div>
</div><!--/.row-->


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">创建</div>
            <div class="panel-body">
                <form action="/index/create" role="form" method="post">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>剧名</label>
                            <input class="form-control" name="name" placeholder="剧名" value="">
                        </div>
                        <div class="form-group">
                            <label>来源</label>
                            <input class="form-control" name="url" placeholder="来源" value="">
                        </div>
                        <button type="submit" class="btn btn-primary">提交</button>
                        <button type="reset" class="btn btn-default">取消</button>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- /.col-->
</div><!-- /.row -->
