{%extends "layout.phtml"%}
{%block title%} {{ title }} {%endblock%}
{%block main%}
<!-- 按钮触发模态框 -->

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
                <li class="active">Tables</li>
            </ol>
        </div><!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}  第{{ season }}季</h1>
            </div>
            
        </div><!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="/list/{{id}}/{{season}}/ed2k">ed2k 优先</a>
                        <a href="/list/{{id}}/{{season}}/magnet">magnet 优先</a>
                    </div>
                    {% for value in eformats %}
                    <div class="panel-body" style="display: none;" id="body_{{ value }}">
                        <button id="button_{{ value }}" class="btn btn-default" data-toggle="modal" data-target="#myModal">下载 {{ value }}</button>
                        <p></p>
                        <table id="main_table_{{ value }}"
                            data-id-field="Id"
                            data-detail-view="true"
                            data-detail-formatter="detailFormatter">
                            <thead>
                            <tr>
                                <th data-checkbox="true"></th>
                                <th data-field="name" data-sortable="true">{{ value }}</th>
                                <th data-field="size" data-sortable="true">SIZE</th>
                                <th data-field="recode_at" data-sortable="true">RecodeAt</th>
                                <th data-field="operate" data-events="operateEvents" data-formatter="operateFormatter">操作</th>
                            </tr>
                            </thead>
                        </table>
                        <p></p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div><!--/.row-->	

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal table</h4>
            </div>
            <div class="modal-body" id="modal-body" onclick="selectText('modal-body')">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content xiaomi-remote">
        </div>
    </div>
</div>
<script>
function operateFormatter(value, row, index) {
    return [
        '<button type="button" class="btn btn-primary btn-xs remote" data-toggle="modal" data-target=".bs-example-modal-lg">小米远程下载</button>'
    ].join('');
}
window.operateEvents = {
    'click .download': function(e, value, row, index){
        var href = "http://d.miwifi.com/d2r/?url=" + Base64.encodeURI(row.url) + "&src=demo"
        //window.open(href);
    },
    'click .remote': function(e, value, row, index){
        var href = "http://d.miwifi.com/d2r/?url=" + Base64.encodeURI(row.url) + "&src=demo"
        var frame = $('<iframe src="'+href+'" width="928" height="630"> </iframe> ');
        $('.xiaomi-remote').html(frame);
    },
    'click .like': function (e, value, row, index) {
        alert('You click like action, row: ' + JSON.stringify(row));
    },
    'click .remove': function (e, value, row, index) {
        $table.bootstrapTable('remove', {
            field: 'id',
            values: [row.id]
        });
    }
};
//var data = {{ downloads|json_encode|raw }}
var data = null;
$.ajax({
    url: "/download/list/{{id}}/{{season}}/{{order}}",    //请求的url地址
    dataType: "json",   //返回格式为json
    async: false, //请求是否异步，默认为异步，这也是ajax重要特性
    type: "GET",   //请求方式
    success: function(response) {
        data = response;
    }
});

for (var key in data) {
    var tableName = '#main_table_'+key;
    var bodyName  = '#body_'+key;
    $(tableName).bootstrapTable({
        data: data[key]
    });
    $(bodyName).show();

    $('#button_'+key).bind('click', function(e){
        var btId = $(this).attr('id');
        btId = btId.replace('button_', '');
        var data = $('#main_table_'+btId).bootstrapTable('getSelections');
        var urls = [];
        for (var i = 0; i < data.length; i++) {
            urls.push(data[i].url);
        }
        $('.modal-body').html(urls.join('\r'));
    });
}

function detailFormatter(index, row){
    return row.url;
}
function selectText(containerid) {
    if (document.selection) {
        var range = document.body.createTextRange();
        range.moveToElementText(document.getElementById(containerid));
        range.select();
    } else if (window.getSelection) {
        var range = document.createRange();
        range.selectNode(document.getElementById(containerid));
        window.getSelection().addRange(range);
    }
}
</script>
{%endblock%}
